### ISSUE TITLE
decrypt output using external tools

### ISSUE THREAD

**Issue by jeroenbaas** [alemigo/cryptfile#1]
It could be helpful to report and demonstrate how to interact with files compatible with external tools.
For instance:
Encrypt a file with cryptfile: how should it be decrypted with openssl? I've tried this but couldn't get it to work:
```openssl enc -d -aes-256-ctr -in encryptedfile.aes -out decryptedfile.ext -kfile aes_key.bin -nosalt -md md5```
similarly, how would someone need to encrypt files with e.g. openssl to be able to decrypt them with cryptfile?
Adding these examples to the documentation can help clarify the portability of the produced outputs.

**Comment by alemigo** [comment]
Unfortunately Cryptfile is not compatible with any other library I know of and uses it's own file format.  It achieves random access by writing blocks of a specified size with their own CTR nonce values, which are stored at the start of each block.  Subsequent writes to an existing block re-encrypt the entire block with a new nonce to prevent vulnerability from nonce reuse.  If you want standardized encryption that will work elsewhere, have a look at pycryptodome.

**Comment by jeroenbaas** [comment]
Ok, thanks, that makes sense. I've been look at gnupg (through pretty-bad-protocol) as well. Neither really have such a neat `with encrypter.open(filelike-dest) as filelike-encrypter:` implementation, which is really what you want when e.g. stream generating a tar file. 

Side comment, but I wanted to use it to stream the tar back to s3 directly. unfortunately your code doesn't play nice with smart_open to write to s3, as their generated file-like doesn't have a seek (as the write handle is a stream, you can't go back). While streaming, you shouldn't need to though.
Example:
```
with smart_open.smart_open('s3://somebucket/key.tar.aes','wb') as fout_s3:
    with cryptfile.open(fout_s3, 'wb', aes_key=aes_key, block_num=5000) as fout_aes:
        with tarfile.open(mode = "w:gz", fileobj = fout_aes) as tar:
            strenc="sometext".encode("utf8")
            file = BytesIO(strenc)
            info = tarfile.TarInfo(name="file_in_tar.txt")
            info.size = len(strenc)
            tar.addfile(tarinfo=info, fileobj=file)
```
this won't work as cryptfile will try to do seeks on the fout_s3 which are not available. I don't know if it is possible to implement cryptfile for writing without the seeks?

**Comment by alemigo** [comment]
ah I see what you are doing now.  I can add a simple class for streaming if helpful.  Also, for using tarfile in stream mode, you will need to use "w|gz" as opposed to "w:gz".

**Comment by jeroenbaas** [comment]
That could indeed be helpful for purging the whole file in one stream. Would make it nicely compatible with smart_open.

re:tarfile mode: I don't observe any difference between those modes, both produces streams that result in chunks being uploaded before the file is completed.

**Comment by alemigo** [comment]
I added cryptfilestream as an option
